http:
  routers:
    fe-hirde:
      rule: "Host(`fe-hirde.no`) || Host(`www.fe-hirde.no`)"
      service: fe-hirde
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    
    # Redirect fehirde.no to fe-hirde.no
    fehirde-redirect:
      rule: "Host(`fehirde.no`) || Host(`www.fehirde.no`)"
      service: noop@internal
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - fehirde-redirect

  services:
    fe-hirde:
      loadBalancer:
        servers:
          - url: "http://nextjs:3000"
        passHostHeader: true

  middlewares:
    fehirde-redirect:
      redirectRegex:
        regex: "^https://fehirde.no/(.*)"
        replacement: "https://fe-hirde.no/${1}"
        permanent: true 